
# This is a basic workflow to help you get started with Actions

name: Second

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["First"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    if: ${{ github.event.workflow_run.cocnclusion == 'success' }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run a one-line script
        run: echo "Running after first workflow!"
